#ng build --configuration production && firebase deploy --only hosting:x100
#kubectl apply -f deploy/sm.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sm
  name: sm
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sm
      tier: web
  template:
    metadata:
      labels:
        app: sm
        tier: web
    spec:
      containers:
      - env:
        - name: DB_PORT
          value: "1433"
        - name: DB_HOST
          value: JETTI-DB-01
        - name: DB_NAME
          value: sm
        - name: DB_USER
          value: jetti
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mssql-db-credentials
        - name: DB_TASK_USER
          value: jetti_task
        - name: DB_TASK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mssql-db-credentials
        - name: REDIS_DB_HOST
          value: redis-master
        - name: JTW_KEY
          valueFrom:
            secretKeyRef:
              key: JTW_KEY
              name: jwt-key
        - name: EXCHANGE_ACCESS_KEY
          value: ei362NQNrfyLMrzJ0fECu1gQn7Hbv1Y5KllJIQGbbgY=
        - name: JETTI_IS_HOST
          value: https://is.jetti-app.com
        - name: REGISTER_ACCUMULATION_SOURCE
          value: "[x100-data]."
        - name: LOGIC_USECASHREQUESTAPPROVING
          value: "1"
        - name: REFRESH_ID
          value: "00002"
        - name: NODE_ENV
          value: production
        image: eu.gcr.io/jetti-x100/jetti-api:latest
        imagePullPolicy: Always
        name: jetti
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sm
  labels:
    app: sm
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: sm
  ports:
  - port: 8080
    targetPort: 8080